# Generated by Django 2.0.2 on 2018-02-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
