# Generated by Django 2.0.2 on 2018-02-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20180205_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='meaning', max_length=20),
            preserve_default=False,
        ),
    ]
